MENUKEY|F7
BIND|X|0|0|0|D:\SteamLibrary\steamapps\common\MGS_TPP\mod\modules\ProneShortcut.lua

[THIS IS JUST A SAMPLE. DON'T INCLUDE THIS IN THE BUILD!]
[THIS FILE IS AUTOMATICALLY CREATED ON THE FIRST RUN ALONG WITH THE FOLDER!]
